config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  
  get "admin" => "admin#index"
  get "user" => "user#index"
  
  get 'admins/sign_out', to: 'admins/sessions#destroy', as: :admin_destroy

  resources :stocks
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTradingApp-Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex">
        <nav class="flex">
            <div class="sticky top-0 w-64 h-screen p-4 bg-gray-600">
                <div class="flex">
                    <h1 class="hidden py-2 font-bold text-md text-gray-50 md:block"><% current_user.email %></h1>
                </div>
                <ul class="flex flex-col text-gray-50">
                    <li>
                        <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'gauge-high', class: "mr-2") %> <span class="hidden md:inline-block">Dashboard</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'cart-shopping', class:'mr-2') %> <span class="hidden md:inline-block">User Management</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'list', class:'mr-2') %> <span class="hidden md:inline-block">User Pending</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'truck-fast', class:'mr-2') %> <span class="hidden md:inline-block">See Transactions</span>
                        <% end %>
                    </li>
                </ul>
                <div>
                    <%= link_to "Sign out", destroy_admin_session_path, method: :delete, data: { turbo_method: :delete } %>
                </div>
            </div>     
        </nav>
        <div class="p-8">
            <%= yield %>
        </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTradingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTradingApp-User</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex">
        <nav class="flex justify-center">
            <div class="sticky top-0 w-64 h-screen p-4 bg-gray-600">
                <div class="flex">
                    <div><%= icon('fa-solid', 'user', class: "mr-2 h-24 w-24") %></div>
                    <h1 class="hidden py-2 font-bold text-md text-gray-50 md:block"><%= current_user.email %></h1>
                </div>
                <ul class="flex flex-col text-gray-50">
                    <li>
                        <%= link_to user_path , class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'briefcase', class: "mr-2") %> <span class="hidden md:inline-block">Portfolio</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to stocks_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'money-bill-trend-up', class: "mr-2") %> <span class="hidden md:inline-block">Stocks</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to user_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'money-bill', class:'mr-2') %> <span class="hidden md:inline-block">Buy/Sell</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to user_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                            <%= icon('fa-solid', 'credit-card', class:'mr-2') %> <span class="hidden md:inline-block">Transactions</span>
                        <% end %>
                    </li>
                </ul>
                <div>
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
                </div>
            </div>           
        </nav>
        <div class="p-8">
            <%= yield %>
        </div>
    </main>
  </body>
</html>